### PR TITLE
[TGL][EHL] Fix GetFwCap HECI communication issue

### LINKED ISSUE #1401: [TGL][EHL] Wrong HECI FW CAP structure was used for command communication.
To get FW capability, SBL sends HECI command.  However, it used GET_FW_CAPS_SKU_ACK_DATA as the buffer for HECI command on TGL and EHL.  It should use GET_FW_CAPS_SKU_ACK instead.

### PR DESCRIPTION
**Pull request by mauricema**
On TGL and EHL, to get FW capability, it will send GetFwCaps
command. However, the ACK buffer structure is used incorrectly.
It should use GET_FW_CAPS_SKU_ACK rather than
GET_FW_CAPS_SKU_ACK_DATA. This patch fixed it.

It fixed #1401.

Signed-off-by: Ma <maurice.ma@intel.com>

### CODE REVIEW

File: Silicon/TigerlakePchPkg/Library/HeciInitLib/MkhiMsgs.h [hunk 1]
```diff
@@ -31,10 +31,16 @@ typedef union {
...
 #define MKHI_CBM_GROUP_ID     0x00
+#define MKHI_FWCAPS_GROUP_ID  0x03
 #define MKHI_HMRFPO_GROUP_ID  0x05
 #define MKHI_MCA_GROUP_ID     0x0A
 #define MKHI_GEN_GROUP_ID     0xFF
 
+///
+/// Defines for FWCAPS_GROUP Command
+///
+#define FWCAPS_GET_RULE_CMD               0x02
```
Comment (japelner-intc) [inline Silicon/TigerlakePchPkg/Library/HeciInitLib/MkhiMsgs.h:42]: Just a nit. Want to align the value with the surrounding ones?

**Review by japelner-intc — APPROVED** [review]
Looks good.

**Comment by koktong-ong** [comment]
Looks good to me

**Review by gdong1 — APPROVED** [review]

File: Silicon/TigerlakePchPkg/Library/HeciInitLib/MkhiMsgs.h (hunk 1 above)
Comment (mauricema) [reply Silicon/TigerlakePchPkg/Library/HeciInitLib/MkhiMsgs.h:42]: sure, I can do that.

Comment (mauricema) [reply Silicon/TigerlakePchPkg/Library/HeciInitLib/MkhiMsgs.h]: fixed it in new commit.
