### PR TITLE
Fix boot performance issue for BP1

### LINKED ISSUE #188: [WHL] Boot performance is very slow when booting from BP1
On WHL with Boot Guard profile 0, if booting from SBL boot partition 1,  the boot time is significantly longer than booting from boot partition 0.

### PR DESCRIPTION
**Pull request by mauricema**
On WHL, if using Boot Guard profile 0, booting from BP1 will be
significantly slower than BP0. It is because some code region in BP1
is not covered by MTRR cache settings. This patch adjusted MTRR
settings during PostTempRamInit notification to cover full flash
code region if Boot Guard profile 0 is used.

It fixed #188.

Signed-off-by: Maurice Ma <maurice.ma@intel.com>

### CODE REVIEW

File: Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c [hunk 1]
```diff
@@ -160,6 +163,24 @@ BoardInit (
...
       SetCurrentBootPartition (BootPartition == BootPartition2 ? 1 : 0);
     }
+
+    // Enlarge the code cache region to cover full flash for non-BootGuard case only
+    if ((AsmReadMsr64 (MSR_BOOT_GUARD_SACM_INFO) & B_BOOT_GUARD_SACM_INFO_NEM_ENABLED) == 0) {
+       // WHL FSP-T does not allow to enable full flash code cache due to cache size restriction.
+       // Here, MTRR is patched to enable full flash region cache to avoid performance penalty.
+       // However, the SBL code flow should ensure only limited flash regions will be accessed
+       // before FSP TempRamExit() is called. The combined DATA and CODE cache size should satisfy
+       // the BWG requirement.
```
Comment (sindhuragrandhi) [inline Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c]: By BWG, do you mean BIOS Writer's Guide?

Comment (mauricema) [reply Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c]: Yes, it is.

**Comment by raghavag** [comment]
Changes look good to me
