### PR TITLE
[APL] Fix boot failure in OsLoader

### LINKED ISSUE #197: [APL] Boot failure when board notifications are called in SBL Stage2
When SBL calls board notification ReadyToBoot and EndOfFirmware in Stage2,  OsLoader will assert on APL platform.  
Debug log as below:
...                                                                                                    
Payload normal heap: 0x4000000 (0xE3A000 used)                                                      
Payload reserved heap: 0x900000 (0x0 used)                                                          
Payload stack: 0x10000 (0x1C00 used)                                                                
                                                                                                    
ASSERT [Stage2] w:\slimboot\slimfork\MdePkg\Library\BaseMemoryLibSse2\ZeroMemWrapper.c(47): Buffer != ((void *) 0)                                                                                      
                                                                                                    
STAGE_2: System halted!

### PR DESCRIPTION
**Pull request by mauricema**
When SBL calls board notification ReadyToBoot and EndOfFirmware in
Stage2, OsLoader will assert on APL platform. It was caused by NULL
pointer access in ClearFspHob(). This patch added NULL pointer check
before zeroing out memory. It fixed #197.

Signed-off-by: Maurice Ma <maurice.ma@intel.com>

### CODE REVIEW

File: Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c [hunk 1]
```diff
@@ -578,9 +578,11 @@ ClearFspHob (
 
   LdrGlobal  = (LOADER_GLOBAL_DATA *)GetLoaderGlobalDataPointer ();
   HandOffHob = (EFI_HOB_HANDOFF_INFO_TABLE  *) LdrGlobal->FspHobList;
-  Length     = (UINT8 *) (UINTN) HandOffHob->EfiEndOfHobList - (UINT8 *)HandOffHob;
-  ZeroMem (HandOffHob, Length);
-  LdrGlobal->FspHobList = NULL;
+  if (HandOffHob != NULL) {
```
Comment (gdong1) [inline Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c]: Do we know why FspHobList could be NULL? we might need update logic to make sure only free it once.

Comment (mauricema) [reply Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c]: FspHobClear() will be called in board notification.  
And FspHobList will be set to NULL.   When in OsLoader, it tries to notify again,  this will happen.

Comment (gdong1) [reply Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c]: Could we also avoid to call FspHobClear() twice?

Comment (mauricema) [reply Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c]: I think this patch will handle it.  When FspHobClear() is called more than once, it will just return.

Comment (gdong1) [reply Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c]: Agree this patch could WA the issue.  At same time, should we avoid it is invoked twice?

Comment (mauricema) [reply Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c]: I think it is better to handle it inside ClearHobClear() to make it work in either way.
ClearHobClear() will be called from board notification.  The board notification should be called only once per notify code.   This is not enforced for now.

Comment (gdong1) [reply Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c]: Some notifications, e.g. EndOfStages, EndOfFirmware should be invoked only once.
I am ok to check this fix firstly and update others code later.

Comment (mauricema) [reply Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c]: OK, let us handle it separately.
For this fix, it is required anyway since it can potentially access NULL pointer.
